repos:
  - repo: local
    hooks:
      - id: normalize-filenames
        name: Normalize Unicode in Filenames to NFC
        entry: python3 .scripts/unicode_normalizer.py
        language: system
        always_run: true
        pass_filenames: false